#ifndef _BUTTON_H_
#define _BUTTON_H_
#include <zephyr/zbus/zbus.h>

/** @brief Types of events generated by the physical button. */
enum button_evt_type {
	BUTTON_EVT_UNDEFINED,
	BUTTON_EVT_PRESSED,
	BUTTON_EVT_RELEASED,
	BUTTON_EVT_LONGPRESS,
};

/** @brief Message structure used to publish button events via ZBus. */
struct msg_button_evt {
	enum button_evt_type evt;
};

/** @brief Declaration of the ZBus channel used for button event communication. */
ZBUS_CHAN_DECLARE(chan_button_evt);

/**
 * @brief Initializes the button.
 *
 * Configures the button based on the Devicetree specification.
 *
 * @retval 0 Success.
 * @retval -ENODEV Button device not ready.
 * @retval <0 Pin configuration error.
 */
int button_init(void);

/**
 * @brief Enables button interrupts.
 *
 * Configures edge triggers and registers the callback.
 *
 * @retval 0 Success.
 * @retval <0 Configuration error.
 */
int button_enable_interrupts(void);

#endif /* _BUTTON_H_ */
